version: "3.8"


services:


  #################################
  # Book: The Book microservice
  #################################
  book:
    image: keithloh2021/book:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/book


  ###############################################
  # callbook: The test_invoke_http.py program
  ###############################################
  callbook:
    image: keithloh2021/callbook:1.0
    depends_on:
      - book
    environment:
      bookURL: http://book:5001/book
